apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJXRENCL3FBREFnRUNBZ0VBTUFvR0NDcUdTTTQ5QkFNQ01DTXhJVEFmQmdOVkJBTU1HR3N6Y3kxelpYSjIKWlhJdFkyRkFNVFUzTURjeE5qYzNNREFlRncweE9URXdNVEF4TkRFeU5UQmFGdzB5T1RFd01EY3hOREV5TlRCYQpNQ014SVRBZkJnTlZCQU1NR0dzemN5MXpaWEoyWlhJdFkyRkFNVFUzTURjeE5qYzNNREJaTUJNR0J5cUdTTTQ5CkFnRUdDQ3FHU000OUF3RUhBMElBQk4rQ245a3dteHMyQ08vR0lzUHQyVElmaDFnM0ZVNUJtWWRSSWxLQ09waXAKaHNTc0Frc3N0K1M3bzRqQytKVmNNMXlJK25HS0tJa0k0VXRHNVVtYlBybWpJekFoTUE0R0ExVWREd0VCL3dRRQpBd0lDcERBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUFvR0NDcUdTTTQ5QkFNQ0Ewa0FNRVlDSVFDa3hKTGFoc2pDClIrOG15WWQ1SGh1S1BSOVAyTXd6Q2lKZEErSHlGZ2MxL1FJaEFOeUloMU0rQmszNVR6aUdpOUx6cks4MVI4YTYKcUt2ampTMDZJdkJUUkgzQQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://127.0.0.1:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    password: c600aa6fc3a96857e779e5f27397ad76
    username: admin
