version: "3.3"
services:

  consul-dc1:
    image: consul:1.6.0
    command: ["consul","agent","-config-file=/config/consul-dc1.hcl"]
    volumes:
      - "../consul_config:/config"
    ports:
      - 8500:8500
    networks:
      dc1:
        ipv4_address: 10.5.0.2
      wan:
        ipv4_address: 192.169.7.2

  # Define web service and envoy sidecar proxy
  web:
    image: nicholasjackson/fake-service:v0.4.1
    environment:
      LISTEN_ADDR: 0.0.0.0:9090
      UPSTREAM_URIS: http://localhost:9091
      MESSAGE: "Hello World"
      NAME: web
      SERVER_TYPE: "http"
      HTTP_CLIENT_KEEP_ALIVES: "false"
    networks:
      dc1:
        ipv4_address: 10.5.0.3
    ports:
      - 9090:9090
  web_envoy:
    image: nicholasjackson/consul-envoy:v1.6.0-v0.10.0
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
      SERVICE_CONFIG: /config/web_v1.hcl
    volumes:
      - "./service_config:/config"
      - "./central_config:/central_config"
    command: ["consul", "connect", "envoy","-sidecar-for", "web-v1"]
    network_mode: "service:web"

  payments_v1:
    image: nicholasjackson/fake-service:v0.4.1
    environment:
      LISTEN_ADDR: localhost:9090
      NAME: payments-dc1
      MESSAGE: "PAYMENTS V1"
    networks:
      dc1:
        ipv4_address: 10.5.0.4
  payments_proxy_v1:
    image: nicholasjackson/consul-envoy:v1.6.0-v0.10.0
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
      SERVICE_CONFIG: /config/payments_v1.hcl
    volumes:
      - "./service_config:/config"
      - "./central_config:/central_config"
    command: ["consul", "connect", "proxy","-sidecar-for", "payments-v1"]
    network_mode: "service:payments_v1"
 
  consul-dc2:
    image: consul:1.6.0
    command: ["consul","agent","-config-file=/config/consul-dc2.hcl"]
    volumes:
      - "../consul_config:/config"
    ports:
      - 9500:8500
    networks:
      dc2:
        ipv4_address: 10.6.0.2
      wan:
        ipv4_address: 192.169.7.4


  # Define api service and envoy sidecar proxy for version 2 of the service
  payments_v2:
    image: nicholasjackson/fake-service:v0.4.1
    environment:
      LISTEN_ADDR: localhost:9090
      NAME: payments-dc2
      MESSAGE: "PAYMENTS V2"
    networks:
      dc2:
        ipv4_address: 10.6.0.3
  payments_proxy_v2:
    image: nicholasjackson/consul-envoy:v1.6.0-v0.10.0
    environment:
      CONSUL_HTTP_ADDR: 10.6.0.2:8500
      CONSUL_GRPC_ADDR: 10.6.0.2:8502
      SERVICE_CONFIG: /config/payments_v2.hcl
    volumes:
      - "./service_config:/config"
      - "./central_config:/central_config"
    command: ["consul", "connect", "proxy","-sidecar-for", "payments-v2"]
    network_mode: "service:payments_v2"

  consul-dc3:
    image: consul:1.6.0
    command: ["consul","agent","-config-file=/config/consul-dc3.hcl"]
    volumes:
      - "../consul_config:/config"
    ports:
      - 7500:8500
    networks:
      dc3:
        ipv4_address: 10.7.0.2
      wan:
        ipv4_address: 192.169.7.5


  # Define api service and envoy sidecar proxy for version 2 of the service
  payments_v3:
    image: nicholasjackson/fake-service:v0.4.1
    environment:
      LISTEN_ADDR: localhost:9090
      NAME: payments-dc3
      MESSAGE: "PAYMENTS V3"
    networks:
      dc3:
        ipv4_address: 10.7.0.3
  payments_proxy_v3:
    image: nicholasjackson/consul-envoy:v1.6.0-v0.10.0
    environment:
      CONSUL_HTTP_ADDR: 10.7.0.2:8500
      CONSUL_GRPC_ADDR: 10.7.0.2:8502
      SERVICE_CONFIG: /config/payments_v3.hcl
    volumes:
      - "./service_config:/config"
      - "./central_config:/central_config"
    command: ["consul", "connect", "proxy","-sidecar-for", "payments-v3"]
    network_mode: "service:payments_v3"

  gateway-dc1:
    image: nicholasjackson/consul-envoy:v1.6.0-v0.10.0
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
    command: [
      "consul",
      "connect", "envoy",
      "-mesh-gateway",
      "-register",
      "-address", "10.5.0.5:443",
      "-wan-address", "192.169.7.3:443",
      "--",
      "-l", "debug"]
    networks:
      dc1:
        ipv4_address: 10.5.0.5
      wan:
        ipv4_address: 192.169.7.3

  gateway-dc2:
    image: nicholasjackson/consul-envoy:v1.6.0-v0.10.0
    environment:
      CONSUL_HTTP_ADDR: 10.6.0.2:8500
      CONSUL_GRPC_ADDR: 10.6.0.2:8502
    command: [
      "consul",
      "connect", "envoy",
      "-mesh-gateway",
      "-register",
      "-address", "10.6.0.5:443",
      "-wan-address", "192.169.7.8:443",
      "--",
      "-l", "debug"]
    networks:
      dc2:
        ipv4_address: 10.6.0.5
      wan:
        ipv4_address: 192.169.7.8

  gateway-dc3:
    image: nicholasjackson/consul-envoy:v1.6.0-v0.10.0
    environment:
      CONSUL_HTTP_ADDR: 10.7.0.2:8500
      CONSUL_GRPC_ADDR: 10.7.0.2:8502
    command: [
      "consul",
      "connect", "envoy",
      "-mesh-gateway",
      "-register",
      "-address", "10.7.0.5:443",
      "-wan-address", "192.169.7.9:443",
      "--",
      "-l", "debug"]
    networks:
      dc3:
        ipv4_address: 10.7.0.5
      wan:
        ipv4_address: 192.169.7.9


networks:
  dc1:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
  dc2:
    driver: bridge
    ipam:
     config:
       - subnet: 10.6.0.0/16
  dc3:
    driver: bridge
    ipam:
     config:
       - subnet: 10.7.0.0/16
  wan:
    driver: bridge
    ipam:
     config:
       - subnet: 192.169.7.0/24
